services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSGRES_DB=upload
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
